[pytest]
testpaths = test
pythonpath = test
addopts = --alluredir=test/support_files/allure-results

markers =
    login: Login scenario tests
    EventHub: EventHub feature tests
    e2e: End-to-end tests
    smoke: Smoke/sanity tests
    regression: Regression tests
